# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Configuration for Gradle dependencies
  - package-ecosystem: "gradle" # Specifies the package manager (Gradle)
    directory: "/" # Location of your build.gradle or build.gradle.kts files
    schedule:
      interval: "weekly" # Check for updates weekly
    open-pull-requests-limit: 5 # Limit to 5 open PRs for these updates
    allow:
      - dependency-type: "all" # Allow updates for all dependency types (direct, indirect)
    #ignore:
      # You can add more ignore rules here for other dependencies if needed
      # - dependency-name: "some.other.dependency"
      #   versions: ["< 2.0.0"] # Example: ignore any version before 2.0.0
