#!/bin/bash

# Script: generate_homebrew_formula.sh
# Purpose: Automates the creation of the Homebrew Ruby formula file.
# Usage: This script is run by the GitHub Actions workflow (.github/workflows/release.yml)
#
# Process:
# 1. Downloads the executable JAR and the launcher script for the specified tag.
# 2. Computes the SHA256 checksums, which are critical for Homebrew's security validation.
# 3. Generates the 'jdkcerts.rb' file with the latest version, URLs, and checksums.

set -euo pipefail

TAG=$1
REPO="ADarko22/JDKCertsTool"
JAR_NAME="jdkcertstool.jar"
SCRIPT_NAME="jdkcerts" # Name of the script asset
JAR_URL="https://github.com/$REPO/releases/download/$TAG/$JAR_NAME"
SCRIPT_URL="https://github.com/$REPO/releases/download/$TAG/$SCRIPT_NAME"

# Download the jar fresh (overwrite if exists)
echo "Downloading $JAR_NAME from $JAR_URL"
curl -L -o "$JAR_NAME" "$JAR_URL"

# Download the script fresh (overwrite if exists)
echo "Downloading $SCRIPT_NAME from $SCRIPT_URL"
curl -L -o "$SCRIPT_NAME" "$SCRIPT_URL"
chmod +x "$SCRIPT_NAME" # Ensure it's executable for local testing if needed

# Compute SHA256 of the downloaded jar
JAR_SHA=$(shasum -a 256 "$JAR_NAME" | awk '{print $1}')
SCRIPT_SHA=$(shasum -a 256 "$SCRIPT_NAME" | awk '{print $1}') # Also get SHA for the script

# Ensure Formula directory exists relative to this script
FORMULA_DIR="$(dirname "$0")/../Formula"
mkdir -p "$FORMULA_DIR"

cat > "$FORMULA_DIR/jdkcerts.rb" <<EOF
# frozen_string_literal: true

# -----------------------------------------------------------------------------
# !!! WARNING !!!
# This file is auto-generated by 'scripts/generate_homebrew_formula.sh'
# DO NOT EDIT THIS FILE MANUALLY. All changes will be overwritten on the next release.
# -----------------------------------------------------------------------------

class Jdkcerts < Formula
  desc "Tool to manage JDK certificates"
  homepage "https://github.com/$REPO"
  url "$JAR_URL"
  version "${TAG#v}"
  sha256 "$JAR_SHA"
  license "Apache-2.0"

  # Defines the bash launcher script as a separate resource
  resource "jdkcerts-script" do
    url "$SCRIPT_URL"
    sha256 "$SCRIPT_SHA"
  end

  # The tool requires a Java environment to run
  depends_on "openjdk"

  # Install the JAR into Homebrew's private library executable directory (libexec)
  def install
    libexec.install "$JAR_NAME"

    # Install the script into the public binary directory (bin)
    resource("jdkcerts-script").stage do
      bin.install "jdkcerts"
      chmod 0755, bin/"jdkcerts"
    end
  end

  # Basic smoke test to ensure the installed command runs
  test do
    assert_match "Usage", shell_output("\#{bin}/jdkcerts --help")
  end
end
EOF

echo "Formula generated at $FORMULA_DIR/jdkcerts.rb"