name: Deploy Documentation

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Initialization
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Configure Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      # 2. Deploy gh pages with mkdocs
      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
